# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_111
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
dist: trusty

language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/
