sudo: false
dist: trusty
cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
before_install:
- git config user.name "$GH_USER"
- git config user.email "$GH_USER_EMAIL"
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- ./travis/publish.sh
branches:
  except:
  - /^[0-9]/
